### ISSUE TITLE
Integration with captcha doesn't work

### ISSUE THREAD

**Issue by unbranched** [thirtybees/blocknewsletter#10]
The No Captcha reCAPTCHA module is correctly working for registrations, logins, etc.
But the integration with this newsletter module keeps answering me:

"Newsletter : your captcha is wrong. Retry."
No visible prompt appears.

I tried Captcha vEnterprise, v3, v2. Currently using v2 Classic.
I'm on thirtybees ~1.4.0~ 1.5.1, latest modules.

**Comment by getdatakick** [comment]
I can't reproduce this, for me captcha is properly displayed.

![image](https://github.com/thirtybees/blocknewsletter/assets/34651851/9f670cce-df8e-44bf-b34c-6fe0c582fdea)


I think that this will be either an issue with some CSS that hides captcha block, and therefore making it impossible to click on it to solve it. Or there may be some javascript error that blocks captcha javascript library to load and initialize captcha html.

**Comment by getdatakick** [comment]
This js error can be the culprit - you are using CCC to build single bundle, so this exception can block the other/subsequent scripts from executing. Script to initialize captcha might never be executed.

Try to disable CCC, moving javascript to bottom, etc., to see if it helps

**Comment by getdatakick** [comment]
![image](https://github.com/thirtybees/blocknewsletter/assets/34651851/3476ee3d-8337-484a-ae8b-e2b85e694485)

**Comment by getdatakick** [comment]
this msg_newsl is different bug, I'll file an issue for it.

I just realized that you probably didn't update niara to latest version. Niara contains its own overrides of tpl / js / css files from this module. If you are not on latest version, then either update using core updater, or apply changes manually: https://github.com/thirtybees/niara/commit/f2cefe304897d2cd15284b4ca0c8f4416a68cdf2

**Comment by getdatakick** [comment]
Related issue: https://github.com/thirtybees/niara/issues/73

**Comment by getdatakick** [comment]
I've just tested update of community themes on my production server (I didn't do that for few years now because I don't use them), and all changes related to commit https://github.com/thirtybees/niara/commit/f2cefe304897d2cd15284b4ca0c8f4416a68cdf2 were pulled and applied correctly.
